"""kolom preferensi usaha di users

Revision ID: 1582121d56f3
Revises: 9e4d9ee584cd
Create Date: 2026-08-23 23:45:37.383385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 - dipakai kolom Geometry hasil autogenerate


# revision identifiers, used by Alembic.
revision: str = '1582121d56f3'
down_revision: Union[str, None] = '9e4d9ee584cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferensi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferensi')
    # ### end Alembic commands ###
