"""pricelens p07 b10, commuter clock per jam, kuadran interaktif

Revision ID: 42f4c91c9026
Revises: c0a56e2aba1e
Create Date: 2026-08-21 08:21:13.003726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 - dipakai kolom Geometry hasil autogenerate


# revision identifiers, used by Alembic.
revision: str = '42f4c91c9026'
down_revision: Union[str, None] = 'c0a56e2aba1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hex_hourly_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('jam', sa.Integer(), nullable=False),
    sa.Column('n_transaksi', sa.Integer(), nullable=False),
    sa.Column('nominal_total', sa.Float(), nullable=True),
    sa.Column('nominal_median', sa.Float(), nullable=True),
    sa.Column('pangsa_captive', sa.Float(), nullable=True),
    sa.Column('metode', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['h3_index'], ['hex_features.h3_index'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('h3_index', 'jam', name='uq_profil_hex_jam')
    )
    op.create_index(op.f('ix_hex_hourly_profiles_h3_index'), 'hex_hourly_profiles', ['h3_index'], unique=False)
    op.add_column('hex_features', sa.Column('belanja_per_jam', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('harga_sewa_per_m2', sa.Float(), nullable=True))
    op.add_column('location_scores', sa.Column('prestise_visual', sa.Float(), nullable=True))
    op.add_column('location_scores', sa.Column('n_metode_lolos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_scores', 'n_metode_lolos')
    op.drop_column('location_scores', 'prestise_visual')
    op.drop_column('hex_features', 'harga_sewa_per_m2')
    op.drop_column('hex_features', 'belanja_per_jam')
    op.drop_index(op.f('ix_hex_hourly_profiles_h3_index'), table_name='hex_hourly_profiles')
    op.drop_table('hex_hourly_profiles')
    # ### end Alembic commands ###
