"""core tables

Revision ID: 67d9b3197c10
Revises: 
Create Date: 2026-08-20 23:05:28.812977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '67d9b3197c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hex_features',
    sa.Column('h3_index', sa.String(), nullable=False),
    sa.Column('kawasan', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('ipt', sa.Float(), nullable=True),
    sa.Column('iae', sa.Float(), nullable=True),
    sa.Column('ikp', sa.Float(), nullable=True),
    sa.Column('ibr', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('hidden_gem_score', sa.Float(), nullable=True),
    sa.Column('zona_izin_komersial', sa.Boolean(), nullable=False),
    sa.Column('n_titik_misi', sa.Integer(), nullable=False),
    sa.Column('tingkat_keyakinan', sa.String(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('h3_index')
    )
    # GeoAlchemy2's Geometry type auto-creates a GiST index on 'geom' via a
    # DDL after_create event — an explicit op.create_index here would collide.
    op.create_table('transport_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('moda', sa.String(), nullable=False),
    sa.Column('kawasan', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('kategori', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['h3_index'], ['hex_features.h3_index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catchment_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_node_id', sa.Integer(), nullable=False),
    sa.Column('menit', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['transport_node_id'], ['transport_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=False),
    sa.Column('harga_sewa_terbaca', sa.Float(), nullable=True),
    sa.Column('confidence_ocr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['h3_index'], ['hex_features.h3_index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(), nullable=False),
    sa.Column('kode_variabel', sa.String(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=True),
    sa.Column('sumber', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['h3_index'], ['hex_features.h3_index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_poi_id', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=False),
    sa.Column('harga_terbaca', sa.Float(), nullable=True),
    sa.Column('confidence_ocr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['business_poi_id'], ['business_pois.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_poi_id', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=False),
    sa.Column('total_belanja', sa.Float(), nullable=True),
    sa.Column('jam_transaksi', sa.String(), nullable=True),
    sa.Column('confidence_ocr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['business_poi_id'], ['business_pois.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: 'spatial_ref_sys' is a PostGIS system table — autogenerate flags it
    # as "removed" because it's not one of our models. Never drop it.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_observations')
    op.drop_table('menu_observations')
    op.drop_table('score_factors')
    op.drop_table('property_observations')
    op.drop_table('catchment_areas')
    op.drop_table('business_pois')
    op.drop_table('transport_nodes')
    op.drop_table('hex_features')
    # ### end Alembic commands ###
