"""akun langganan token pemantauan

Revision ID: 9e4d9ee584cd
Revises: 42f4c91c9026
Create Date: 2026-08-23 21:21:23.675793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 - dipakai kolom Geometry hasil autogenerate


# revision identifiers, used by Alembic.
revision: str = '9e4d9ee584cd'
down_revision: Union[str, None] = '42f4c91c9026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pengguna', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('sidik_sandi', sa.String(length=255), nullable=False),
    sa.Column('nama_tampilan', sa.String(length=80), nullable=True),
    sa.Column('peran', sa.String(length=20), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('saldo_token', sa.Integer(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('terakhir_masuk', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nama_pengguna'), 'users', ['nama_pengguna'], unique=True)
    op.create_table('premium_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('jenis', sa.String(length=30), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'h3_index', 'jenis', name='uq_unlock')
    )
    op.create_index(op.f('ix_premium_unlocks_h3_index'), 'premium_unlocks', ['h3_index'], unique=False)
    op.create_index(op.f('ix_premium_unlocks_user_id'), 'premium_unlocks', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paket', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('selamanya', sa.Boolean(), nullable=False),
    sa.Column('harga_rp', sa.Integer(), nullable=True),
    sa.Column('dimulai_pada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('berlaku_sampai', sa.DateTime(), nullable=True),
    sa.Column('metode_bayar', sa.String(length=20), nullable=False),
    sa.Column('referensi_bayar', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('token_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('keperluan', sa.String(length=40), nullable=False),
    sa.Column('catatan', sa.String(length=200), nullable=True),
    sa.Column('h3_index', sa.String(length=20), nullable=True),
    sa.Column('saldo_sesudah', sa.Integer(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_ledger_user_id'), 'token_ledger', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('catatan', sa.String(length=200), nullable=True),
    sa.Column('skor_saat_dipantau', sa.Float(), nullable=True),
    sa.Column('versi_saat_dipantau', sa.String(length=40), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'h3_index', name='uq_watchlist')
    )
    op.create_index(op.f('ix_watchlist_items_h3_index'), 'watchlist_items', ['h3_index'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_h3_index'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_token_ledger_user_id'), table_name='token_ledger')
    op.drop_table('token_ledger')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_premium_unlocks_user_id'), table_name='premium_unlocks')
    op.drop_index(op.f('ix_premium_unlocks_h3_index'), table_name='premium_unlocks')
    op.drop_table('premium_unlocks')
    op.drop_index(op.f('ix_users_nama_pengguna'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
