"""kamus data final 41 variabel

Revision ID: c0a56e2aba1e
Revises: 67d9b3197c10
Create Date: 2026-08-21 00:22:24.013953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 - dipakai kolom Geometry hasil autogenerate


# revision identifiers, used by Alembic.
revision: str = 'c0a56e2aba1e'
down_revision: Union[str, None] = '67d9b3197c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fitur', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('input_ref', sa.Text(), nullable=True),
    sa.Column('output_ringkas', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('perlu_review', sa.Boolean(), nullable=False),
    sa.Column('biaya_usd', sa.Float(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('versi', sa.String(length=40), nullable=False),
    sa.Column('ipt', sa.Float(), nullable=True),
    sa.Column('iae', sa.Float(), nullable=True),
    sa.Column('ikp', sa.Float(), nullable=True),
    sa.Column('ibr', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('hidden_gem_score', sa.Float(), nullable=True),
    sa.Column('residual_biaya', sa.Float(), nullable=True),
    sa.Column('iptt', sa.Float(), nullable=True),
    sa.Column('kuadran', sa.String(length=20), nullable=True),
    sa.Column('peringkat', sa.Integer(), nullable=True),
    sa.Column('dihitung_pada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['h3_index'], ['hex_features.h3_index'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('h3_index', 'versi', name='uq_score_hex_versi')
    )
    op.create_index(op.f('ix_location_scores_h3_index'), 'location_scores', ['h3_index'], unique=False)
    op.create_index(op.f('ix_location_scores_hidden_gem_score'), 'location_scores', ['hidden_gem_score'], unique=False)
    op.create_index(op.f('ix_location_scores_opportunity_score'), 'location_scores', ['opportunity_score'], unique=False)
    op.add_column('business_pois', sa.Column('kelas_induk', sa.String(length=4), nullable=False))
    op.add_column('business_pois', sa.Column('kategori_asli', sa.String(length=200), nullable=True))
    op.add_column('business_pois', sa.Column('sumber', sa.String(length=20), nullable=False))
    op.add_column('business_pois', sa.Column('is_waralaba', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_business_pois_h3_index'), 'business_pois', ['h3_index'], unique=False)
    op.drop_constraint('business_pois_h3_index_fkey', 'business_pois', type_='foreignkey')
    op.drop_column('business_pois', 'kategori')
    op.create_index(op.f('ix_catchment_areas_transport_node_id'), 'catchment_areas', ['transport_node_id'], unique=False)
    op.create_unique_constraint('uq_catchment_node_menit', 'catchment_areas', ['transport_node_id', 'menit'])
    op.drop_constraint('catchment_areas_transport_node_id_fkey', 'catchment_areas', type_='foreignkey')
    op.create_foreign_key(None, 'catchment_areas', 'transport_nodes', ['transport_node_id'], ['id'], ondelete='CASCADE')
    op.add_column('hex_features', sa.Column('pop_100m', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('pop_usia_produktif', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('jarak_simpul_m', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('waktu_jalan_menit', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('skor_simpul', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('ridership_proksi', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('kepadatan_kos', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('kepadatan_kantor', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('generator_keramaian', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('skor_ramai_terkoreksi', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('intensitas_transaksi', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('aktivitas_komunitas', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('puncak_pagi', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('puncak_siang', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('puncak_sore', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('puncak_malam', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('rasio_weekend', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('pangsa_digital', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('harga_median_porsi', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('spread_harga', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('nominal_median_struk', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('n_kompetitor_langsung', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('kepadatan_poi_total', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('keragaman_usaha', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('keragaman_kuliner', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('pangsa_waralaba', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('rasio_kompetitor_per_kapita', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('rasio_keliling', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('n_menetap_kuliner', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('njop_m2', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('njop_persentil', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('pasokan_sewa_komersial', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('rasio_sewa_jual', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('harga_sewa_median', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('indeks_churn', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('kelas_zona', sa.String(length=40), nullable=True))
    op.add_column('hex_features', sa.Column('risiko_banjir', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('rasio_tutupan_bangunan', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('luas_bangunan_median', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('skor_prestise_visual', sa.Float(), nullable=True))
    op.add_column('hex_features', sa.Column('diperbarui_pada', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('hex_features', 'zona_izin_komersial',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_hex_features_kawasan'), 'hex_features', ['kawasan'], unique=False)
    op.create_index('ix_hex_keyakinan', 'hex_features', ['tingkat_keyakinan'], unique=False)
    op.drop_column('hex_features', 'ibr')
    op.drop_column('hex_features', 'opportunity_score')
    op.drop_column('hex_features', 'ipt')
    op.drop_column('hex_features', 'iae')
    op.drop_column('hex_features', 'ikp')
    op.drop_column('hex_features', 'hidden_gem_score')
    op.add_column('menu_observations', sa.Column('h3_index', sa.String(length=20), nullable=False))
    op.add_column('menu_observations', sa.Column('nama_usaha', sa.String(length=200), nullable=True))
    op.add_column('menu_observations', sa.Column('kondisi_pembeli', sa.String(length=10), nullable=True))
    op.add_column('menu_observations', sa.Column('waktu_kunjungan', sa.DateTime(), nullable=True))
    op.add_column('menu_observations', sa.Column('mobilitas_keliling', sa.Boolean(), nullable=True))
    op.add_column('menu_observations', sa.Column('harga_rata_porsi', sa.Float(), nullable=True))
    op.add_column('menu_observations', sa.Column('menu_andalan', sa.Text(), nullable=True))
    op.add_column('menu_observations', sa.Column('kelas_kuliner', sa.String(length=40), nullable=True))
    op.add_column('menu_observations', sa.Column('surveyor_id', sa.String(length=60), nullable=True))
    op.add_column('menu_observations', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False))
    op.create_index(op.f('ix_menu_observations_h3_index'), 'menu_observations', ['h3_index'], unique=False)
    op.drop_constraint('menu_observations_business_poi_id_fkey', 'menu_observations', type_='foreignkey')
    op.drop_column('menu_observations', 'harga_terbaca')
    op.drop_column('menu_observations', 'business_poi_id')
    op.drop_column('menu_observations', 'foto_url')
    op.drop_column('menu_observations', 'confidence_ocr')
    op.add_column('property_observations', sa.Column('kategori', sa.String(length=60), nullable=True))
    op.add_column('property_observations', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('property_observations', sa.Column('foto_spanduk_url', sa.Text(), nullable=True))
    op.add_column('property_observations', sa.Column('harga_nominal', sa.Float(), nullable=True))
    op.add_column('property_observations', sa.Column('periode', sa.String(length=20), nullable=True))
    op.add_column('property_observations', sa.Column('luas_m2', sa.Float(), nullable=True))
    op.add_column('property_observations', sa.Column('skor_prestise', sa.Float(), nullable=True))
    op.add_column('property_observations', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    op.add_column('property_observations', sa.Column('ocr_terverifikasi', sa.Boolean(), nullable=False))
    op.add_column('property_observations', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False))
    op.create_index(op.f('ix_property_observations_h3_index'), 'property_observations', ['h3_index'], unique=False)
    op.drop_constraint('property_observations_h3_index_fkey', 'property_observations', type_='foreignkey')
    op.drop_column('property_observations', 'foto_url')
    op.drop_column('property_observations', 'harga_sewa_terbaca')
    op.drop_column('property_observations', 'confidence_ocr')
    op.add_column('receipt_observations', sa.Column('h3_index', sa.String(length=20), nullable=False))
    op.add_column('receipt_observations', sa.Column('nama_merchant', sa.String(length=200), nullable=True))
    op.add_column('receipt_observations', sa.Column('waktu_transaksi', sa.DateTime(), nullable=True))
    op.add_column('receipt_observations', sa.Column('metode_bayar', sa.String(length=40), nullable=True))
    op.add_column('receipt_observations', sa.Column('total_nominal', sa.Float(), nullable=True))
    op.add_column('receipt_observations', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    op.add_column('receipt_observations', sa.Column('ocr_terverifikasi', sa.Boolean(), nullable=False))
    op.add_column('receipt_observations', sa.Column('surveyor_id', sa.String(length=60), nullable=True))
    op.add_column('receipt_observations', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False))
    op.alter_column('receipt_observations', 'foto_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_receipt_observations_h3_index'), 'receipt_observations', ['h3_index'], unique=False)
    op.drop_constraint('receipt_observations_business_poi_id_fkey', 'receipt_observations', type_='foreignkey')
    op.drop_column('receipt_observations', 'total_belanja')
    op.drop_column('receipt_observations', 'jam_transaksi')
    op.drop_column('receipt_observations', 'business_poi_id')
    op.drop_column('receipt_observations', 'confidence_ocr')
    op.add_column('score_factors', sa.Column('versi', sa.String(length=40), nullable=False))
    op.add_column('score_factors', sa.Column('indeks', sa.String(length=4), nullable=False))
    op.add_column('score_factors', sa.Column('nilai_mentah', sa.Float(), nullable=True))
    op.add_column('score_factors', sa.Column('nilai_normalisasi', sa.Float(), nullable=True))
    op.add_column('score_factors', sa.Column('persentil', sa.Float(), nullable=True))
    op.add_column('score_factors', sa.Column('kontribusi', sa.Float(), nullable=True))
    op.create_index(op.f('ix_score_factors_h3_index'), 'score_factors', ['h3_index'], unique=False)
    op.drop_constraint('score_factors_h3_index_fkey', 'score_factors', type_='foreignkey')
    op.create_foreign_key(None, 'score_factors', 'hex_features', ['h3_index'], ['h3_index'], ondelete='CASCADE')
    op.drop_column('score_factors', 'nilai')
    op.drop_column('score_factors', 'sumber')
    op.add_column('transport_nodes', sa.Column('jumlah_jalur', sa.Integer(), nullable=True))
    op.add_column('transport_nodes', sa.Column('ridership_harian', sa.Float(), nullable=True))
    op.create_index(op.f('ix_transport_nodes_kawasan'), 'transport_nodes', ['kawasan'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transport_nodes_kawasan'), table_name='transport_nodes')
    op.drop_column('transport_nodes', 'ridership_harian')
    op.drop_column('transport_nodes', 'jumlah_jalur')
    op.add_column('score_factors', sa.Column('sumber', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('score_factors', sa.Column('nilai', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'score_factors', type_='foreignkey')
    op.create_foreign_key('score_factors_h3_index_fkey', 'score_factors', 'hex_features', ['h3_index'], ['h3_index'])
    op.drop_index(op.f('ix_score_factors_h3_index'), table_name='score_factors')
    op.drop_column('score_factors', 'kontribusi')
    op.drop_column('score_factors', 'persentil')
    op.drop_column('score_factors', 'nilai_normalisasi')
    op.drop_column('score_factors', 'nilai_mentah')
    op.drop_column('score_factors', 'indeks')
    op.drop_column('score_factors', 'versi')
    op.add_column('receipt_observations', sa.Column('confidence_ocr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('receipt_observations', sa.Column('business_poi_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('receipt_observations', sa.Column('jam_transaksi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('receipt_observations', sa.Column('total_belanja', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('receipt_observations_business_poi_id_fkey', 'receipt_observations', 'business_pois', ['business_poi_id'], ['id'])
    op.drop_index(op.f('ix_receipt_observations_h3_index'), table_name='receipt_observations')
    op.alter_column('receipt_observations', 'foto_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('receipt_observations', 'geom')
    op.drop_column('receipt_observations', 'surveyor_id')
    op.drop_column('receipt_observations', 'ocr_terverifikasi')
    op.drop_column('receipt_observations', 'ocr_confidence')
    op.drop_column('receipt_observations', 'total_nominal')
    op.drop_column('receipt_observations', 'metode_bayar')
    op.drop_column('receipt_observations', 'waktu_transaksi')
    op.drop_column('receipt_observations', 'nama_merchant')
    op.drop_column('receipt_observations', 'h3_index')
    op.add_column('property_observations', sa.Column('confidence_ocr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('property_observations', sa.Column('harga_sewa_terbaca', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('property_observations', sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key('property_observations_h3_index_fkey', 'property_observations', 'hex_features', ['h3_index'], ['h3_index'])
    op.drop_index(op.f('ix_property_observations_h3_index'), table_name='property_observations')
    op.drop_column('property_observations', 'geom')
    op.drop_column('property_observations', 'ocr_terverifikasi')
    op.drop_column('property_observations', 'ocr_confidence')
    op.drop_column('property_observations', 'skor_prestise')
    op.drop_column('property_observations', 'luas_m2')
    op.drop_column('property_observations', 'periode')
    op.drop_column('property_observations', 'harga_nominal')
    op.drop_column('property_observations', 'foto_spanduk_url')
    op.drop_column('property_observations', 'status')
    op.drop_column('property_observations', 'kategori')
    op.add_column('menu_observations', sa.Column('confidence_ocr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('menu_observations', sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('menu_observations', sa.Column('business_poi_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('menu_observations', sa.Column('harga_terbaca', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('menu_observations_business_poi_id_fkey', 'menu_observations', 'business_pois', ['business_poi_id'], ['id'])
    op.drop_index(op.f('ix_menu_observations_h3_index'), table_name='menu_observations')
    op.drop_column('menu_observations', 'geom')
    op.drop_column('menu_observations', 'surveyor_id')
    op.drop_column('menu_observations', 'kelas_kuliner')
    op.drop_column('menu_observations', 'menu_andalan')
    op.drop_column('menu_observations', 'harga_rata_porsi')
    op.drop_column('menu_observations', 'mobilitas_keliling')
    op.drop_column('menu_observations', 'waktu_kunjungan')
    op.drop_column('menu_observations', 'kondisi_pembeli')
    op.drop_column('menu_observations', 'nama_usaha')
    op.drop_column('menu_observations', 'h3_index')
    op.add_column('hex_features', sa.Column('hidden_gem_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hex_features', sa.Column('ikp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hex_features', sa.Column('iae', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hex_features', sa.Column('ipt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hex_features', sa.Column('opportunity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hex_features', sa.Column('ibr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index('ix_hex_keyakinan', table_name='hex_features')
    op.drop_index(op.f('ix_hex_features_kawasan'), table_name='hex_features')
    op.alter_column('hex_features', 'zona_izin_komersial',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('hex_features', 'diperbarui_pada')
    op.drop_column('hex_features', 'skor_prestise_visual')
    op.drop_column('hex_features', 'luas_bangunan_median')
    op.drop_column('hex_features', 'rasio_tutupan_bangunan')
    op.drop_column('hex_features', 'risiko_banjir')
    op.drop_column('hex_features', 'kelas_zona')
    op.drop_column('hex_features', 'indeks_churn')
    op.drop_column('hex_features', 'harga_sewa_median')
    op.drop_column('hex_features', 'rasio_sewa_jual')
    op.drop_column('hex_features', 'pasokan_sewa_komersial')
    op.drop_column('hex_features', 'njop_persentil')
    op.drop_column('hex_features', 'njop_m2')
    op.drop_column('hex_features', 'n_menetap_kuliner')
    op.drop_column('hex_features', 'rasio_keliling')
    op.drop_column('hex_features', 'rasio_kompetitor_per_kapita')
    op.drop_column('hex_features', 'pangsa_waralaba')
    op.drop_column('hex_features', 'keragaman_kuliner')
    op.drop_column('hex_features', 'keragaman_usaha')
    op.drop_column('hex_features', 'kepadatan_poi_total')
    op.drop_column('hex_features', 'n_kompetitor_langsung')
    op.drop_column('hex_features', 'nominal_median_struk')
    op.drop_column('hex_features', 'spread_harga')
    op.drop_column('hex_features', 'harga_median_porsi')
    op.drop_column('hex_features', 'pangsa_digital')
    op.drop_column('hex_features', 'rasio_weekend')
    op.drop_column('hex_features', 'puncak_malam')
    op.drop_column('hex_features', 'puncak_sore')
    op.drop_column('hex_features', 'puncak_siang')
    op.drop_column('hex_features', 'puncak_pagi')
    op.drop_column('hex_features', 'aktivitas_komunitas')
    op.drop_column('hex_features', 'intensitas_transaksi')
    op.drop_column('hex_features', 'skor_ramai_terkoreksi')
    op.drop_column('hex_features', 'generator_keramaian')
    op.drop_column('hex_features', 'kepadatan_kantor')
    op.drop_column('hex_features', 'kepadatan_kos')
    op.drop_column('hex_features', 'ridership_proksi')
    op.drop_column('hex_features', 'skor_simpul')
    op.drop_column('hex_features', 'waktu_jalan_menit')
    op.drop_column('hex_features', 'jarak_simpul_m')
    op.drop_column('hex_features', 'pop_usia_produktif')
    op.drop_column('hex_features', 'pop_100m')
    op.drop_constraint(None, 'catchment_areas', type_='foreignkey')
    op.create_foreign_key('catchment_areas_transport_node_id_fkey', 'catchment_areas', 'transport_nodes', ['transport_node_id'], ['id'])
    op.drop_constraint('uq_catchment_node_menit', 'catchment_areas', type_='unique')
    op.drop_index(op.f('ix_catchment_areas_transport_node_id'), table_name='catchment_areas')
    op.add_column('business_pois', sa.Column('kategori', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('business_pois_h3_index_fkey', 'business_pois', 'hex_features', ['h3_index'], ['h3_index'])
    op.drop_index(op.f('ix_business_pois_h3_index'), table_name='business_pois')
    op.drop_column('business_pois', 'is_waralaba')
    op.drop_column('business_pois', 'sumber')
    op.drop_column('business_pois', 'kategori_asli')
    op.drop_column('business_pois', 'kelas_induk')
    op.drop_index(op.f('ix_location_scores_opportunity_score'), table_name='location_scores')
    op.drop_index(op.f('ix_location_scores_hidden_gem_score'), table_name='location_scores')
    op.drop_index(op.f('ix_location_scores_h3_index'), table_name='location_scores')
    op.drop_table('location_scores')
    op.drop_table('ai_call_logs')
    # ### end Alembic commands ###
