"""tabel hex_routes untuk rute jalan kaki ORS

Revision ID: c22ddbceff30
Revises: 1582121d56f3
Create Date: 2026-08-24 23:43:42.127139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 - dipakai kolom Geometry hasil autogenerate


# revision identifiers, used by Alembic.
revision: str = 'c22ddbceff30'
down_revision: Union[str, None] = '1582121d56f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hex_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('transport_node_id', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('jarak_m', sa.Float(), nullable=False),
    sa.Column('menit', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('profil', sa.String(length=24), nullable=False),
    sa.Column('dihitung_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['h3_index'], ['hex_features.h3_index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transport_node_id'], ['transport_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('h3_index', 'transport_node_id', 'urutan', name='uq_rute_hex_simpul_urutan')
    )
    op.create_index(op.f('ix_hex_routes_h3_index'), 'hex_routes', ['h3_index'], unique=False)
    op.create_index(op.f('ix_hex_routes_transport_node_id'), 'hex_routes', ['transport_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hex_routes_transport_node_id'), table_name='hex_routes')
    op.drop_index(op.f('ix_hex_routes_h3_index'), table_name='hex_routes')
    op.drop_table('hex_routes')
    # ### end Alembic commands ###
